### ISSUE TITLE
Forge does not fail on installing non-existent repo, should properly scope installs

### ISSUE THREAD

**Issue by sambacha** [gakonst/foundry#767] opened 2022-02-18 02:41 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (8e100cf 2022-02-17T22:55:47.862863+00:00)

### What command(s) is the bug in?

forge install dapptools/ds-test

### Operating System

macOS (amd)

### Describe the bug

when running forge install on a non-existent github repo, forge will produce a successful install message in the terminal 

e.g.

```sh
$ forge install dapptools/ds-test
Installing ds-test in "/Users/devusr/workspace-contracts/lib/ds-test", (url: https://github.com/dapptools/ds-test, tag: None)
    Installed ds-test
```

This should fail as their is no ds-test repo for dapptools (its located at dapphub/ds-test)

additionally, forge install @uniswap/v3-core leaves the install dir at v3-core, can this the scoped package name be the top most directory, i.e. @uniswap?

**Comment by onbjerg** [comment] 2022-02-19 15:19
There is no @uniswap/v3-core repository, so it would assume that @uniswap is the owner of the v3-core repository and place it in a submodule named after the repository. I guess we could support an additional name flag or parameter to configure this, but I am not sure how that would affect remappings and the UX of the CLI.

I think the bug in this issue is caused by us not checking for the exit code of the install commands here: https://github.com/gakonst/foundry/blob/master/cli/src/cmd/install.rs (we just make sure they finish running). Marking this as a good first issue for that reason

**Comment by sambacha** [comment] 2022-02-25 06:54
Closed by https://github.com/gakonst/foundry/pull/779

**Closed** 2022-02-25 06:54 UTC
Labels: T-bug, good first issue, C-forge, D-easy, Cmd-forge-pm

**Comment by sambacha** [comment] 2022-02-25 06:57
> There is no @uniswap/v3-core repository, so it would assume that @uniswap is the owner of the v3-core repository and place it in a submodule named after the repository. I guess we could support an additional name flag or parameter to configure this, but I am not sure how that would affect remappings and the UX of the CLI.
> 
> 
> 
> I think the bug in this issue is caused by us not checking for the exit code of the install commands here: https://github.com/gakonst/foundry/blob/master/cli/src/cmd/install.rs (we just make sure they finish running). Marking this as a good first issue for that reason

Yes I would not change the existing remapping logic just for this, hence why I am proposing this https://github.com/gakonst/foundry/issues/786

Thanks for the quick turnaround
