### ISSUE TITLE
Don't print the entire bytecode

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#905] opened 2022-03-11 08:32 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest

### What command(s) is the bug in?

forge test

### Describe the bug

if a test deploys bytecode the verbosity is set to 3 it logs the entirety of the bytecode. this should rather be 4bytes...4bytes

![telegram-cloud-photo-size-1-4996976393862621699-y](https://user-images.githubusercontent.com/19890894/157831156-e504e7a9-ed0e-4a46-ae69-4f1ffeeadfa0.jpg)

![telegram-cloud-photo-size-1-4996976393862621700-x](https://user-images.githubusercontent.com/19890894/157831227-dc3ff2a6-2995-47d8-b0a9-0b919426b7b7.jpg)

**Comment by onbjerg** [comment] 2022-03-12 16:30
I'm not sure I understand where this happens, AFAIK current Forge does not do traces for constructors, and creates in subcalls should be minimized to what the 2nd screenshot shows

**Comment by onbjerg** [comment] 2022-03-21 11:07
I can't reproduce this, I've tried using factory contracts in and outside of `setUp`, passing or reverting, nothing works 🤔

**Comment by onbjerg** [comment] 2022-03-27 07:34
Going to close this as it is unreproducible and I couldn't get original reporter in Foundry chat to reply with an example - can always reopen if this is still an issue

**Closed by onbjerg** 2022-03-27 07:34 UTC
Labels: T-bug, Cmd-forge-test, A-tracing, D-easy
