### ISSUE TITLE
Forge install hangs when installing non existing repositories

### ISSUE THREAD

**Issue by sambacha** [gakonst/foundry#712] opened 2022-02-09 21:57 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

running `forge install solmate` causes forge to hang instead of producing an exception, as forge is trying to install ` https://github.com/solmate`. - forge  install Rari-Capital/solmate correctly resolves to the git repo.

**Comment by gakonst** [comment] 2022-02-10 18:56
I cannot reproduce this locally, just ran `forge install asdf` and it completed, although it did say "Installed asdf" instead of producing an error.

**Comment by onbjerg** [comment] 2022-02-12 18:04
Was this fixed in #719?

**Closed** 2022-02-12 18:09 UTC
Labels: T-bug, C-forge, Cmd-forge-pm
