### ISSUE TITLE
Signed binary blob

### ISSUE THREAD

**Issue by Magicking** [gakonst/foundry#661] opened 2022-02-03 07:51 UTC
### Component

Other (please describe)

### Describe the feature you would like

Signed binary blob to avoid downloading untrusted binary blob on a computer

**Comment by onbjerg** [comment] 2022-02-05 20:42
Is this related to/a dupe of #495? Or do you want us to sign the release?

**Comment by gakonst** [comment] 2022-02-09 12:26
I think that we're not going to be adding signed blobs anytime soon, so let's focus on the checksums

**Closed by gakonst** 2022-02-09 12:26 UTC
Labels: A-releases
