### ISSUE TITLE
Forge url fork not working

### ISSUE THREAD

**Issue by ChinmayGopal931** [gakonst/foundry#548] opened 2022-01-22 23:08 UTC
On the latest forge version and can't get the test to connect to RPC node.  I am using this command to test :
forge test --fork-url https://mainnet.infura.io/v3/c978b74938064a98b67a150e4ade294d -vvv

And Here is the code I am using:

```
contract HelloWorldTest is DSTest {
    HelloWorld hello;
        IERC20  dai;

    function setUp() public {
    dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
      hello = new HelloWorld("Foundry is fast!");
    }


    function test1() public {
        console.log(dai.balanceOf(0x7705e47bd6eb6dc5a11aa1839639f3dc6e1a6eaf));
```        

Here is the stack trace
```
chinmay@chinmay-x1carbon:~/final$ forge test --fork-url https://mainnet.infura.io/v3/c978b74938064a98b67a150e4ade294d -vvv
compiling...
no files changed, compilation skipped.
Running 2 tests for HelloWorldTest.json:HelloWorldTest
[FAIL. Reason: ] test1() (gas: 3092)
Traces:
  [264575] HelloWorldTest::setUp()
    ├─ → new HelloWorld@0xce71…c246
    │   └─ ← 920 bytes of code
    └─ ← ()
  [3092] HelloWorldTest::test1()
    ├─ [0] 0x6b17…1d0f::70a08231(000000000000000000000000bebc44782c7db0a1a60cb6fe97d0b483032ff1c7)
    │   └─ ← ()
    └─ ← ()


Failed tests:
[FAIL. Reason: ] test1() (gas: 3092)

```

**Comment by onbjerg** [comment] 2022-01-22 23:26
Is that the complete snippet, or should it be:

```solidity
contract HelloWorldTest is DSTest {
    HelloWorld hello;
        IERC20  dai;

    function setUp() public {
    dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
      hello = new HelloWorld("Foundry is fast!");
    }


    function test1() public {
        console.log(dai.balanceOf(0x7705e47bd6eb6dc5a11aa1839639f3dc6e1a6eaf));
   }
}

```

**Comment by ChinmayGopal931** [comment] 2022-01-22 23:31
> Is that the complete snippet, or should it be:
> 
> ```solidity
> // imports here?
> 
> contract HelloWorldTest is DSTest {
>     HelloWorld hello;
>         IERC20  dai;
> 
>     function setUp() public {
>     dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
>       hello = new HelloWorld("Foundry is fast!");
>     }
> 
> 
>     function test1() public {
>         console.log(dai.balanceOf(0x7705e47bd6eb6dc5a11aa1839639f3dc6e1a6eaf));
>    }
> }
> ```

Yes, this is the code. Where you able to reproduce this?

**Comment by onbjerg** [comment] 2022-01-22 23:38
Yeah I was able to reproduce this.

**Comment by onbjerg** [comment] 2022-01-22 23:44
Should be fixed in https://github.com/gakonst/foundry/pull/542, I've queued up a release. When the release is done please run `foundryup` and try again :)

**Comment by onbjerg** [comment] 2022-01-22 23:53
Since the Linux version was released before the others I've been able to test this on the latest nightly and confirmed it works.

**Closed by onbjerg** 2022-01-22 23:53 UTC
Labels: bug, test, forge
