### ISSUE TITLE
`forge create` not working `0: could not find artifact`

### ISSUE THREAD

**Issue by Rolstenhouse** [gakonst/foundry#778] opened 2022-02-20 20:37 UTC
Running into an issue on first contract deploy to local ganache

Running on M1 hardware

```forge create --rpc-url 127.0.0.1:7545 --private-key <private_key> src/Token.sol
compiling...
Compiling 9 files with 0.8.10
Compilation finished successfully
Compiler run successful
success.
Error:
   0: could not find artifact```

More logs 
```Location:
   /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/eyre-0.6.6/src/lib.rs:1164
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: _main<unknown>
      at <unknown source file>:<unknown line>
   2: _main<unknown>
      at <unknown source file>:<unknown line>
   3: _main<unknown>
      at <unknown source file>:<unknown line>
   4: _main<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: _main<unknown>
      at <unknown source file>:<unknown line>```

**Comment by gakonst** [comment] 2022-02-20 22:00
Can you share the code and command used to produce this error?

**Comment by Rolstenhouse** [comment] 2022-02-20 22:34
```
forge init test_2
cd init test_2
forge build 
forge create --rpc-url 127.0.0.1:7545 --private-key <private_key> src/Contract.sol
```

Same error generated with and without ganache running

No code changed - so just the outpu from running init. Smells like an issue w/ rust installation, but not sure if anyone has run into it before

**Comment by onbjerg** [comment] 2022-02-21 05:27
What's the contents of `out` and how did you install Foundry?

**Comment by Rolstenhouse** [comment] 2022-02-22 19:24
Installation `curl -L https://foundry.paradigm.xyz | bash` (ran this over the weekend (feb 20)
Contents of `out`

```
├── Contract.sol
│   └── Contract.json
├── Contract.t.sol
│   └── ContractTest.json
└── test.sol
    └── DSTest.json
```

Contract.json

{
  "abi": [],
  "bytecode": {
    "object": "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212208823ff6a670f1a7eb3a71ffdcad48c52acc8cd43bd1aacd3d177c90c261881cb64736f6c634300080a0033",
    "sourceMap": "64:20:1:-:0;;;;;;;;;;;;;;;;;;;",
    "linkReferences": {}
  },
  "deployedBytecode": {
    "object": "0x6080604052600080fdfea26469706673582212208823ff6a670f1a7eb3a71ffdcad48c52acc8cd43bd1aacd3d177c90c261881cb64736f6c634300080a0033",
    "sourceMap": "64:20:1:-:0;;;;;",
    "linkReferences": {}
  }
}

ContractTest.json
{
  "abi": [
    {
      "type": "function",
      "name": "IS_TEST",
      "inputs": [],
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "failed",
      "inputs": [],
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "setUp",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "testExample",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "log",
      "inputs": [
        {
          "name": "",
          "type": "string",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_address",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_bytes",
      "inputs": [
        {
          "name": "",
          "type": "bytes",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_bytes32",
      "inputs": [
        {
          "name": "",
          "type": "bytes32",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_int",
      "inputs": [
        {
          "name": "",
          "type": "int256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_address",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "address",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_bytes",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "bytes",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_bytes32",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "bytes32",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_decimal_int",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "int256",
          "indexed": false
        },
        {
          "name": "decimals",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_decimal_uint",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "uint256",
          "indexed": false
        },
        {
          "name": "decimals",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_int",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "int256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_string",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "string",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_uint",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_string",
      "inputs": [
        {
          "name": "",
          "type": "string",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_uint",
      "inputs": [
        {
          "name": "",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "logs",
      "inputs": [
        {
          "name": "",
          "type": "bytes",
          "indexed": false
        }
      ],
      "anonymous": false
    }
  ],
  "bytecode": {
    "object": "0x60806040526000805460ff1916600117905534801561001d57600080fd5b5060b48061002c6000396000f3fe6080604052348015600f57600080fd5b506004361060465760003560e01c80630a9254e414604b5780633f5a4a2a14604b578063ba414fa614604d578063fa7626d4146072575b600080fd5b005b600054605e90610100900460ff1681565b604051901515815260200160405180910390f35b600054605e9060ff168156fea2646970667358221220b4fa16ae20c146ff22bbab99de19d181d5fabd76305418290d7b2b2376bab4c364736f6c634300080a0033",
    "sourceMap": "92:135:2:-:0;;;1573:26:0;;;-1:-1:-1;;1573:26:0;1595:4;1573:26;;;92:135:2;;;;;;;;;;;;;;;;",
    "linkReferences": {}
  },
  "deployedBytecode": {
    "object": "0x6080604052348015600f57600080fd5b506004361060465760003560e01c80630a9254e414604b5780633f5a4a2a14604b578063ba414fa614604d578063fa7626d4146072575b600080fd5b005b600054605e90610100900460ff1681565b604051901515815260200160405180910390f35b600054605e9060ff168156fea2646970667358221220b4fa16ae20c146ff22bbab99de19d181d5fabd76305418290d7b2b2376bab4c364736f6c634300080a0033",
    "sourceMap": "92:135:2:-:0;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;130:26;;1605:18:0;;;;;;;;;;;;;;;179:14:3;;172:22;154:41;;142:2;127:18;1605::0;;;;;;;1573:26;;;;;;;;",
    "linkReferences": {}
  }
}

DSTest.json
{
  "abi": [
    {
      "type": "function",
      "name": "IS_TEST",
      "inputs": [],
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "failed",
      "inputs": [],
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "log",
      "inputs": [
        {
          "name": "",
          "type": "string",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_address",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_bytes",
      "inputs": [
        {
          "name": "",
          "type": "bytes",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_bytes32",
      "inputs": [
        {
          "name": "",
          "type": "bytes32",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_int",
      "inputs": [
        {
          "name": "",
          "type": "int256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_address",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "address",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_bytes",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "bytes",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_bytes32",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "bytes32",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_decimal_int",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "int256",
          "indexed": false
        },
        {
          "name": "decimals",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_decimal_uint",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "uint256",
          "indexed": false
        },
        {
          "name": "decimals",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_int",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "int256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_string",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "string",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_named_uint",
      "inputs": [
        {
          "name": "key",
          "type": "string",
          "indexed": false
        },
        {
          "name": "val",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_string",
      "inputs": [
        {
          "name": "",
          "type": "string",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "log_uint",
      "inputs": [
        {
          "name": "",
          "type": "uint256",
          "indexed": false
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "logs",
      "inputs": [
        {
          "name": "",
          "type": "bytes",
          "indexed": false
        }
      ],
      "anonymous": false
    }
  ],
  "bytecode": {
    "object": "0x60806040526000805460ff19166001179055348015601c57600080fd5b50609e8061002b6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063ba414fa6146037578063fa7626d414605c575b600080fd5b600054604890610100900460ff1681565b604051901515815260200160405180910390f35b60005460489060ff168156fea2646970667358221220e4c34e2e16456733565e192dde40b5e160d8545271cc44ae57d269563a91096864736f6c634300080a0033",
    "sourceMap": "716:14223:0:-:0;;;1573:26;;;-1:-1:-1;;1573:26:0;1595:4;1573:26;;;716:14223;;;;;;;;;;;;;;;;",
    "linkReferences": {}
  },
  "deployedBytecode": {
    "object": "0x6080604052348015600f57600080fd5b506004361060325760003560e01c8063ba414fa6146037578063fa7626d414605c575b600080fd5b600054604890610100900460ff1681565b604051901515815260200160405180910390f35b60005460489060ff168156fea2646970667358221220e4c34e2e16456733565e192dde40b5e160d8545271cc44ae57d269563a91096864736f6c634300080a0033",
    "sourceMap": "716:14223:0:-:0;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1605:18;;;;;;;;;;;;;;;179:14:3;;172:22;154:41;;142:2;127:18;1605::0;;;;;;;1573:26;;;;;;;;",
    "linkReferences": {}
  }
}

**Comment by gakonst** [comment] 2022-02-22 19:39
What does `forge --version` and `which forge` output? If `forge` is under `~/.cargo/bin`, you must `rm -rf ~/.cargo/bin/forge`

**Comment by VirtualVizier** [comment] 2022-02-23 00:05
Hey! I am having a similar issue. I am running on an ubuntu desktop with an x86 cpu though.

This is the error I get, when I run `forge create`:
```
Error: 
   0: could not find artifact

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/eyre-0.6.6/src/lib.rs:1164

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
```

This is what I get when I run `forge --version`:
forge 0.1.0 (6547691 2022-02-21T00:27:10.478113793+00:00)

This is what I get when I run `which forge`:
/home/user/.foundry/bin/forge

**Comment by welps** [comment] 2022-02-27 23:56
> ```
> forge init test_2
> cd init test_2
> forge build 
> forge create --rpc-url 127.0.0.1:7545 --private-key <private_key> src/Contract.sol
> ```

@Rolstenhouse this error is caused by not providing the name of the contract. You only provided `src/Contract.sol` when it should be either `Contract` (name of contract) or `src/Contract.sol:Contract`. 

#819 will return a clearer error to highlight the formats accepted by the create/verify-contract commands.

**Comment by mattsse** [comment] 2022-02-28 11:33
Closing with #819
reopen if this is still an issue

**Closed by mattsse** 2022-02-28 11:33 UTC
Labels: T-bug, C-forge, P-high, Cmd-forge-create
