### ISSUE TITLE
Problem with forge build

### ISSUE THREAD

**Issue by Sweng0d** [gakonst/foundry#1117] opened 2022-03-29 08:29 UTC
The application panicked (crashed).
Message:  failed to extract from provider: Error { tag: Tag(Default, 2), profile: Some(Profile(Uncased { string: "default" })), metadata: Some(Metadata { name: "Backwards compat provider", source: None, provide_location: Some(Location { file: "config/src/lib.rs", line: 785, col: 14 }), interpolater:  }), path: [], kind: Message("newline in string found at line 5 column 88"), prev: Some(Error { tag: Tag(Default, 2), profile: Some(Profile(Uncased { string: "default" })), metadata: Some(Metadata { name: "Backwards compat provider", source: None, provide_location: Some(Location { file: "config/src/lib.rs", line: 785, col: 14 }), interpolater:  }), path: [], kind: Message("newline in string found at line 5 column 88"), prev: None }) }
Location: config/src/lib.rs:286

**Comment by mattsse** [comment] 2022-03-29 12:40
I believe this was resolved and was caused by a missing `'` quote? if that's from tg

**Comment by onbjerg** [comment] 2022-03-29 12:44
I think it is, so I'm going to close it. Feel free to ask us to re-open if we are mistaken @Sweng0d :smile:

**Closed by onbjerg** 2022-03-29 12:44 UTC
Labels: T-bug, C-forge, P-high, Cmd-forge-build
