### ISSUE TITLE
Randomly getting `ERROR ethers_solc::compile: Releases request timed out: Elapsed(())`

### ISSUE THREAD

**Issue by xphoniex** [gakonst/foundry#616] opened 2022-01-28 16:16 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (2f6148f 2022-01-28T15:26:17.178549775+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Running `forge build` or `test` randomly emits an error at the beginning:

```
$ forge test
compiling...
Jan 28 19:31:57.208 ERROR ethers_solc::compile: Releases request timed out: Elapsed(())
```

**Comment by onbjerg** [comment] 2022-01-28 18:17
Is your internet connection spotty by any chance? :thinking: This is from svm-rs, a dependency of ethers-solc we use to manage Solidity versions with.

**Comment by odyslam** [comment] 2022-01-28 19:02
@onbjerg I thought the same thing, but I assume it shouldn't surface an error if it hasn't internet? Or this error comes up if it starts with internet and loses it in the process

**Comment by ualtinok** [comment] 2022-01-30 14:46
Today I was working in a place where there was no internet availability and I realized forge was running very quickly. I realized that it's due to solc release check was failing immediately due to having no internet:

`ERROR ethers_solc::compile: ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("binaries.soliditylang.org")), port: None, path: "/macosx-amd64/list.json", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) })`

I always thought the slow start was due to compilation cache check but forge checking solc releases at every run. It this necessary? I think releases should be cached or at least there should be a startup option to skip cause without that code path, startup is super fast. (can reproduce the effect by disconnecting fully)

**Comment by ualtinok** [comment] 2022-01-30 15:03
Okay, using --no-auto-detect and putting solc into path covers the above request. Still wonder why we need to do check releases on every run.

**Comment by gakonst** [comment] 2022-01-30 19:19
We had originally handled this in https://github.com/gakonst/ethers-rs/issues/751, by making the timeout 3 seconds. Should we maybe reconsider? @mattsse

**Comment by mattsse** [comment] 2022-01-30 20:45
that would make sense to store the releases, rn we query the endpoint to get all hashes for the checksum, 

the 3 seconds turned out to be too optimistic, but I already added an offline mode in the solc rewrite, so this timeout will be phased out and could be replaced with a `~/.foundry/cache/solc-releases` lookup.

However this is now a bit unsound if we're checking foundry paths from ethers-solc, which I guess is fine.

**Comment by iainnash** [comment] 2022-02-01 00:35
Would be amazing to add an offline mode. I feel that it's a bit of an anti-pattern to require internet access to run a compile step. Another case this may be problematic is if there is a build step behind an VPS firewall. Caching this or keeping it in a package / config would be great.

It looks like running with `--no-auto-detect` fixes the signature failure I'm getting when I attempt to run offline.

**Comment by mattsse** [comment] 2022-02-01 00:47
yeah exactly, `--no-auto-detect` is currently being abused for that.
there'll be an --offline flag, shortly.
The reason why we need network access is bc we're querying `https://binaries.soliditylang.org/` if solc `auto-detect` is enabled so we can install missing solc versions on demand. Ideally, we want to make this offline first.
these are all ethers-rs issues and tracked there https://github.com/gakonst/ethers-rs/

**Comment by mattsse** [comment] 2022-03-05 19:34
fixed on ethers now

**Closed by mattsse** 2022-03-05 19:34 UTC
Labels: T-bug, Cmd-forge-test, C-forge, Cmd-forge-run, Cmd-forge-build
